import { expect, test, type Locator } from "@playwright/test";
import { isRecord } from "@/shared/guards";
import { installApiFixtures, json, seedSignedInSession } from "./fixtures/api";
import { assetResolutionFixture, searchFixture } from "./feature-map/search-fixtures";
import { expectNavigation } from "./fixtures/navigation-budget";
const detailAddress = "0x2222222222222222222222222222222222222222";
async function box(locator: Locator) {
  const rect = await locator.boundingBox();
  if (!rect) throw new Error("Expected a visible control");
  return rect;
}

for (const viewport of [{ width: 390, height: 844 }, { width: 1280, height: 800 }]) test(`floating asset search preserves its Home origin, detail return and history at ${viewport.width}px`, async ({ page }) => {
  await seedSignedInSession(page); await installApiFixtures(page);
  await page.route("**/api/invest/search?*", (route) => json(route, searchFixture(new URL(route.request().url()).searchParams.get("q") ?? "")));
  let assetReads = 0;
  await page.route("**/api/invest/asset?*", (route) => { assetReads += 1; return json(route, assetResolutionFixture(new URL(route.request().url()).searchParams.get("assetId") ?? "")); });
  await page.setViewportSize(viewport); await page.goto("/home");
  await expect.poll(() => page.evaluate(() => performance.getEntriesByName("session:verified", "mark").length)).toBeGreaterThan(0);
  await page.evaluate(() => window.scrollTo(0, 120));
  const originY = await page.evaluate(() => scrollY);
  const opener = page.getByRole("button", { name: "Search assets", exact: true });
  await opener.click();
  const input = page.getByRole("textbox", { name: "Search assets" });
  await expect(input).toBeFocused();
  await expect(page.getByRole("dialog", { name: "Search assets" })).toBeVisible();
  await expect(page.locator("main[data-app-main-authenticated]")).toHaveAttribute("inert");
  await input.pressSequentially("ORB");
  await expect(input).toHaveValue("ORB");
  await expectNavigation(page, /\/home\?search=ORB$/);
  const rows = page.getByRole("region", { name: "Search results" }).getByRole("button", { name: /Orbit/ });
  await expect(rows).toHaveCount(3);
  await page.setViewportSize({ width: viewport.width, height: 260 });
  const scroll = page.locator("[data-asset-search-scroll]");
  await scroll.evaluate((node) => { node.scrollTop = 70; });
  const savedScroll = await scroll.evaluate((node) => node.scrollTop);
  expect(savedScroll).toBeGreaterThan(0);
  await rows.nth(1).click();
  await expectNavigation(page, new RegExp(`/invest/base:${detailAddress}$`));
  await expect(page.locator("[data-shell-header-title]")).toContainText("Orbit");
  await expect.poll(async () => {
    const detailState: unknown = await page.evaluate(() => {
      const state: unknown = history.state;
      return state;
    });
    return isRecord(detailState) ? detailState.investDetailFrom : null;
  }).toBe("search");
  expect(assetReads).toBe(0);
  await page.getByRole("button", { name: "Back", exact: true }).click();
  await expectNavigation(page, /\/home\?search=ORB$/);
  await expect(input).toHaveValue("ORB"); await expect(rows).toHaveCount(3);
  await expect.poll(() => scroll.evaluate((node) => node.scrollTop)).toBe(savedScroll);
  await expect(rows.nth(1)).toBeFocused();
  await page.goForward(); await expectNavigation(page, new RegExp(`/invest/base:${detailAddress}$`));
  await page.reload(); await expect(page.locator("[data-shell-header-title]")).toContainText("Orbit");
  await page.getByRole("button", { name: "Back", exact: true }).click();
  await expectNavigation(page, /\/home\?search=ORB$/);
  await expect(rows).toHaveCount(3);
  await expect(rows.nth(1)).toBeFocused();
  await page.reload(); await expect(input).toHaveValue("ORB"); await expect(input).not.toBeFocused();
  await expect(rows).toHaveCount(3);
  await page.setViewportSize(viewport);
  await page.getByRole("button", { name: "Clear search" }).click(); await expect(input).toBeFocused();
  await expect(input).toHaveValue(""); await expect(page.getByRole("region", { name: "Search results" })).toHaveCount(0);
  await expectNavigation(page, /\/home\?search=$/);
  await page.getByRole("button", { name: "Close search" }).click(); await expectNavigation(page, /\/home$/);
  await expect(opener).toBeFocused();
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(originY);
  await page.goForward(); await expect(input).toBeVisible();
  await input.press("Escape"); await expect(opener).toBeFocused();
});

for (const closeSearch of ["Escape", "Close", "Back"] as const) test(`asset search field shares the navigation gap and restores keyboard-hidden focus after ${closeSearch}`, async ({ page }) => {
  await seedSignedInSession(page); await installApiFixtures(page);
  await page.route("**/api/invest/search?*", (route) => json(route, searchFixture("ORB")));
  await page.setViewportSize({ width: 320, height: 640 }); await page.goto("/home");
  const nav = page.locator('nav[aria-label="Main navigation"]:not(#desktop-rail nav)');
  const pill = await box(nav);
  const restingGap = 640 - pill.y - pill.height;
  const opener = page.getByRole("button", { name: "Search assets" });
  const circle = await box(opener);
  expect(circle.x - pill.x - pill.width).toBeCloseTo(8, 0); expect(circle.y).toBe(pill.y);
  await opener.click(); const input = page.getByRole("textbox", { name: "Search assets" }); await input.fill("ORB");
  const close = await box(page.getByRole("button", { name: "Close search" }));
  expect(close.x).toBe(circle.x); expect(close.y).toBe(circle.y);
  await expect(page.getByRole("region", { name: "Search results" }).getByRole("button", { name: /Orbit/ })).toHaveCount(3);
  await page.evaluate(() => { const viewport = visualViewport; if (!viewport) throw new Error("Expected visual viewport"); Object.defineProperty(viewport, "height", { configurable: true, value: 340 }); viewport.dispatchEvent(new Event("resize")); });
  await expect(page.locator("html")).toHaveAttribute("data-shell-keyboard", "open");
  await expect.poll(async () => { const bar = await box(page.locator("[data-asset-search-bar]")); return 340 - bar.y - bar.height; }).toBeCloseTo(restingGap, 0);
  await page.locator("[data-asset-search-scroll]").evaluate((node) => { node.scrollTop = node.scrollHeight; });
  const last = await box(page.getByRole("region", { name: "Search results" }).getByRole("button", { name: /Orbit/ }).last());
  expect(last.y + last.height).toBeLessThan((await box(page.locator("[data-asset-search-bar]"))).y);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  if (closeSearch === "Escape") await input.press("Escape");
  else if (closeSearch === "Close") await page.getByRole("button", { name: "Close search" }).click();
  else await page.goBack();
  await expect(opener).toBeFocused();
  await expect(page.locator("html")).not.toHaveAttribute("data-shell-keyboard", "open");
});

for (const reducedMotion of ["no-preference", "reduce"] as const) test(`search close mid-enter and immediate reopen preserve focus with ${reducedMotion}`, async ({ page }) => {
  await seedSignedInSession(page); await installApiFixtures(page);
  await page.route("**/api/invest/search?*", (route) => json(route, searchFixture(new URL(route.request().url()).searchParams.get("q") ?? "")));
  await page.emulateMedia({ reducedMotion });
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/home");
  await expect.poll(() => page.evaluate(() => performance.getEntriesByName("session:verified", "mark").length)).toBeGreaterThan(0);
  await expect(page.getByRole("button", { name: "Search assets" })).toBeVisible();
  const state = await page.evaluate(async () => {
    const opener = [...document.querySelectorAll<HTMLButtonElement>("[data-shell-search-opener]")].find((button) => button.getClientRects().length > 0);
    if (!opener) throw new Error("Expected search opener");
    opener.click();
    const first = document.querySelector<HTMLInputElement>('input[aria-label="Search assets"]');
    const focusedInsideTap = document.activeElement === first;
    const closed = new Promise<void>((resolve) => window.addEventListener("popstate", () => requestAnimationFrame(() => resolve()), { once: true }));
    document.querySelector<HTMLButtonElement>('button[aria-label="Close search"]')?.click();
    await closed;
    const exit = document.querySelector("#asset-search-surface");
    const exitingIsInert = !exit || (exit.hasAttribute("inert") && exit.getAttribute("aria-hidden") === "true");
    const next = [...document.querySelectorAll<HTMLButtonElement>("[data-shell-search-opener]")].find((button) => button.getClientRects().length > 0);
    if (!next) throw new Error("Expected restored opener");
    const restoredFocus = document.activeElement === next;
    next.click();
    const reopened = document.querySelector<HTMLInputElement>('input[aria-label="Search assets"]');
    return { focusedInsideTap, exitingIsInert, restoredFocus, reopenedFocus: document.activeElement === reopened, value: reopened?.value };
  });
  expect(state).toEqual({ focusedInsideTap: true, exitingIsInert: true, restoredFocus: true, reopenedFocus: true, value: "" });
  const input = page.getByRole("textbox", { name: "Search assets" });
  await input.pressSequentially("ORB"); await expect(input).toHaveValue("ORB");
  await expectNavigation(page, /\/home\?search=ORB$/);
  await expect(page.getByRole("region", { name: "Search results" }).getByRole("button", { name: /Orbit/ })).toHaveCount(3);
  const settledReopen = await page.evaluate(async () => {
    const closed = new Promise<void>((resolve) => window.addEventListener("popstate", () => requestAnimationFrame(() => resolve()), { once: true }));
    document.querySelector<HTMLButtonElement>('button[aria-label="Close search"]')?.click();
    await closed;
    [...document.querySelectorAll<HTMLButtonElement>("[data-shell-search-opener]")].find((button) => button.getClientRects().length > 0)?.click();
    const field = document.querySelector<HTMLInputElement>('input[aria-label="Search assets"]');
    return { value: field?.value, focused: document.activeElement === field, search: location.search };
  });
  expect(settledReopen).toEqual({ value: "", focused: true, search: "?search=" });
  await expect(input).toHaveValue("");
  await expect(page.getByRole("region", { name: "Search results" })).toHaveCount(0);
  await expectNavigation(page, /\/home\?search=$/);
  await input.pressSequentially("B"); await expect(input).toHaveValue("B");
  await input.pressSequentially("TC"); await expect(input).toHaveValue("BTC");
  await expectNavigation(page, /\/home\?search=BTC$/);
  await expect(page.getByRole("region", { name: "Search results" }).getByRole("button", { name: /Bitcoin/ })).toHaveCount(1);
  await expect(page.getByRole("button", { name: /Orbit/ })).toHaveCount(0);
  await expect(input).toBeFocused();
  await page.goBack(); await expect(page.getByRole("button", { name: "Search assets" })).toBeFocused();
  await page.goForward(); await expect(input).toBeVisible(); await expect(input).not.toBeFocused();
});
